# Generated by Django 3.1.6 on 2021-02-20 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_uid', models.CharField(max_length=16, null=True)),
                ('file_name', models.CharField(max_length=255, null=True)),
                ('file_size', models.CharField(max_length=255, null=True)),
                ('file_document', models.FileField(upload_to='media/uploaded_files/')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='uid')),
            ],
        ),
        migrations.CreateModel(
            name='ConvertedDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_uid', models.CharField(max_length=16, null=True)),
                ('file_name', models.CharField(max_length=255, null=True)),
                ('file_size', models.CharField(max_length=255, null=True)),
                ('file_document', models.FileField(upload_to='media/converted_files/')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='uid')),
            ],
        ),
    ]
